version: '3'
services:
    web_app:
        container_name: game
        build: docker/
        working_dir: /var/www/html/app
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./:/var/www/html
        ports:
            - '3000:3000'
        command: "npm run dev"
        tty: true